### ISSUE TITLE
How to run a test with the training weigths you have already provided

### ISSUE THREAD

**Issue by Aryanjb** [JotaBravo/spacecraft-uda#10]
Thank you for the work. I would like just to test this network with the training weights you have already provided and my test dataset would be small containing 20 images from lightbox images. Could you please explain how I can use your model just to test lightbox images and get output with pose-estimated images.

Thank you.

**Comment by JotaBravo** [comment]
Hi, 

You can import the model and load the weights with .load_state_dict. Then feed the input images making sure they are in a tensor format.

It is a pretty standard operation in pytorch, so any basic tutorial should help you: e.g. https://discuss.pytorch.org/t/how-to-test-a-pytorch-model-to-processing-images-and-videos/91229
