### ISSUE TITLE
The training time of baseline module?

### ISSUE THREAD

**Issue by huangk77** [JotaBravo/spacecraft-uda#11]
Hi! Thanks for your nice work.  
I would like to know the training time of baseline module?  I use the hourglass module to train the synthesis image of SPEED+, with batch size 4, and it take 2 hours each epoch.  Is it normal for training?

**Comment by JotaBravo** [comment]
Hi, thanks for the interest.

Yes those are some normal times, the hourglass model is quite large and slow to train. Maybe you can see a slight improvement if you can use more cores for the data loader, but I'm afraid those are normal times.

Best,
