### ISSUE TITLE
share your paper ?

### ISSUE THREAD

**Issue by jinzhenmu** [JotaBravo/spacecraft-uda#2]
hi, nice work. 
I find this work useful,and where is your paper link? Is it published online? or anywhere?

**Comment by JotaBravo** [comment]
hi thanks for reaching out, the paper will appear in the ECCV 2022 workshop proceedings. Sorry I have set the repository as private again, but I believe it is not in working conditions. I'll reach out to once is ready for final usage.

**Comment by JotaBravo** [comment]
Dear junzhenmu,

The repo is open again and you should be able to get the paper from arxiv https://arxiv.org/abs/2212.13415

Sorry for keeping you waiting
