### ISSUE TITLE
How to get the gt of the key points in the pictures？

### ISSUE THREAD

**Issue by LiKrP** [JotaBravo/spacecraft-uda#3]
Hello,

Congratulations，and thanks for releasing the code.
I am trying to recreate your results, but i don't know how to get the gt of the kpts.
Is the code available on this repository?

Thanks

**Comment by JotaBravo** [comment]
Hi,

Sorry for the delay, it's been a busy week. 

What do you mean by the gt of the kpts?. Do you mean how to generate the heatmaps and the keypoint positons?

I'll upload the code soon to generate both. In the meantime you can download them from the Mega and OneDrive links.

Best

**Comment by LiKrP** [comment]
Yes，sorry for my unclear statement.

Thanks for your help and patience.

**Comment by JotaBravo** [comment]
I also added the kpts.mat file if that I believe was missing. Please let me know if there is anything I can assist further
